name: apolloApp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^6.1.2
  firebase_messaging: ^9.1.1
  firebase_core: ^1.0.3
  cloud_firestore: ^1.0.4
  firebase_storage: ^8.0.3
  firebase_auth: ^1.0.3
  introduction_screen: ^2.1.0
  first_time_screen: ^1.0.3
  loading: ^1.0.2
  curved_navigation_bar: ^0.3.7
  google_fonts: ^2.0.0
  flutter_swiper: ^1.1.6
  animations: ^2.0.0
  loop_page_view: ^1.0.11
  table_calendar: ^2.3.3
  splashscreen: ^1.3.5
  after_layout: ^1.0.7+2
  js: ^0.6.3
  provider: ^5.0.0
  datetime_picker_formfield: ^2.0.0
  flutter_time_picker_spinner: ^1.0.6+1
  flutter_cupertino_localizations: ^1.0.1
  animated_text_kit: ^3.1.2
  chewie: ^1.0.0
  lottie: ^1.0.1
  video_player: ^2.0.2
  flutter_native_splash: ^1.1.4+1
  smooth_page_indicator: ^0.2.1
  hexcolor: ^2.0.3
  carousel_slider: ^3.0.0
  url_launcher: ^6.0.2
  webview_flutter: ^2.0.2
  flutter_statusbar_manager: ^2.0.0
  flutter_local_notifications: ^5.0.0
  flutter_speed_dial: ^3.0.5
  keyboard_actions: ^3.4.0
  path_provider: ^2.0.1
  flutter_launcher_icons: ^0.9.0
  flutter_statusbarcolor: ^0.2.3
  speech_to_text: ^4.1.0-nullsafety
  avatar_glow: ^2.0.1
  sqflite:
  path:
  google_nav_bar: ^5.0.3
  line_icons: ^2.0.1
  glassmorphism: ^1.0.6
  transparent_image: ^2.0.0
  bubble_tab_indicator: ^0.1.6
  fl_chart: ^0.35.0
  random_string: ^2.1.0
  font_awesome_flutter: ^9.0.0
  google_sign_in: ^5.0.1
  email_validator: ^2.0.1
  auto_size_text: ^2.1.0
  flutter_easyloading: ^3.0.0
  flutter_neumorphic: ^3.1.0
  flutter_spinkit: ^5.0.0
  audioplayers: ^0.18.3
  pull_to_refresh: ^1.6.5
  flare_flutter: ^3.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter_native_splash:
  color: "#130d26"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_launcher.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lottie/
    - assets/images/
    - assets/audios/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
fonts:
  - family: PoppinsTest
    fonts:
      - asset: fonts/Poppins-Medium.ttf
        weight: 500
      - asset: fonts/Poppins-SemiBold.ttf
        weight: 600
        style: bold
    

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
